### ISSUE TITLE
configparser.DuplicateOptionError

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vim-wakatime#112]
I also hit the same issue yesterday from nowhere. `~/.wakatime` doesn't exists since before. Created it and put `wakatime-cli-linux-amd64` there (from https://github.com/wakatime/wakatime-cli/releases/tag/v1.28.3), then I got the following error:

```
Traceback (most recent call last):
  File "/home/chicopaec/.local/share/nvim/plugged/vim-wakatime/scripts/install_cli.py", line 127, in parseConfigFile
    configs.readfp(fh)
  File "/usr/lib/python3.9/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.9/configparser.py", line 1096, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/home/chicopaec/.wakatime.cfg' [line 10]: option 'api_key' in section 'settings' already exists
```

Checking `~/.wakatime.cfg` (which seems misplaced, isn't it supposed to be inside the `~/.wakatime` directory?), the `api_key` key is appearing many times. Deleting all the entries but one makes things work again.

Thing is, the error didn't start appearing until after a week of no data I started noticing that there was no data, and the error didn't appear until I enabled debug mode and saw the same error as @GopherJ put above.

Someone seems to have majorly fucked up a migration or deploy of a new version of Wakatime, and unfortunately things seems mismanaged enough that I now have to cancel my subscription and find a different service that works reliably, or at least tells me when it doesn't work.

_Originally posted by @chicopaec in https://github.com/wakatime/vim-wakatime/issues/109#issuecomment-970328220_

**Comment by alanhamlett** [comment]
What happened there is we started using Python for installing & updating wakatime-cli. Python's INI config parser by default doesn't like duplicate keys, and your `~/.wakatime.cfg` must have contained duplicate keys before but it was ignored until we rolled out the Python `install_cli.py` script.

I've fixed your issue with 31834fe5bdc220d3677eeb42fafffdead8fc6926.
