### ISSUE TITLE
Errors when running WakatimeToday

### ISSUE THREAD

**Issue by reconlx** [wakatime/vim-wakatime#134]
```py
Today: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/wakatime", line 5, in <module>
    from wakatime.__init__ import execute
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/__init__.py", line 17, in <module>
    from .main import execute
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/main.py", line 32, in <module>
    from .api import send_heartbeats, get_time_today
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/api.py", line 22, in <module>
    from .session_cache import SessionCache
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/session_cache.py", line 26, in <module>
    from .packages import requests
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/wakatime/packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

installed using packer.nvim

**Comment by IsaccBarker** [comment]
That's the same issue I had... It's doing this because it's using the legacy Python CLI, whereas it should be using the new Go one. Install the Go CLI, uninstall the Python CLI, and it *should* work. #132.

**Comment by reconlx** [comment]
@IsaccBarker The Go CLI is automatically installed when i install the plugin with packer.nvim correct? I initially did that but i faced this error
`'/Users/limxuan/.wakatime/wakatime-cli' '--today'`
so i went looking around and downloaded the python cli, any idea whats causing the error here?

I opened "wakatime-cli" file and it shows
`The operation can’t be completed because the original item for “wakatime-cli” can’t be found.`

**Comment by reconlx** [comment]
I have identified the issue, im on apple silicone so I'm supposed to use `.wakatime/wakatime-cli-darwin-arm64` instead of `.wakatime/wakatime-cli`, how am I supposed to change it from `.wakatime/wakatime-cli` to `.wakatime/wakatime-cli-darwin-arm64`?

I don't see an option to do it in the [config file](https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md#ini-config-file)

**Comment by IsaccBarker** [comment]
Same here (Apple Silicone wise). I briefly looked through the code and didn't find anything that allows you to change anything from the config file either (just in case it was undocumented).
The Go CLI was never installed when I installed Wakatime on my machine. This was not the behavior on my Linux machine; it did install the Go CLI even with the python CLI and was smart enough to switch over. It must be an issue with Apple Silicone, if I'm not mistaken.
Again, I solved it by just uninstalling the Python CLI and installing the Go CLI manually, but what I suppose you could do is add a couple lines to your (neo)vim config renaming the 'wakatime-cli-darwin-arm64' file to 'wakatime-cli'. This looks kinda complicated to do in vimscript, but if you're using neovim Lua makes it much easier.

**Comment by reconlx** [comment]
thanks for replying, i changed the filename and it works fine now :D
