### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by FeliciousX** [wakatime/vim-wakatime#17]
`Traceback (most recent call last):
File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime-cli.py", line 20, i
 sys.exit(wakatime.main(sys.argv))
 File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/__init__.py", line
 stats = get_file_stats(args.targetFile)
 File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/stats.py", line 92,
 dependencies = parser.parse()
 File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/languages/__init__.
 dependencies = plugin.parse()
 File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/languages/templates
self._process_token(token, content)
File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/languages/templates
self._process_tag(token, content)
File "/home/feliciousx/.vim/bundle/vim-wakatime/plugin/packages/wakatime/wakatime/languages/templates
self.tags.pop(0)`

This keep appearing on my buffer and annoys me. Any ideas to why?

**Comment by alanhamlett** [comment]
An extra closing tag in an html file causes this exception, but it's fixed now. Updating to v3.0.5 of vim-wakatime will fix it for you.

**Comment by FeliciousX** [comment]
Thanks for the quick response :+1:
