### ISSUE TITLE
Does not track time from Neovim

### ISSUE THREAD

**Issue by sovetnik** [wakatime/vim-wakatime#64]
Some days ago wakatime stop sending project activity. Maybe, it bug?

When I enable debug, in log I see only heartbeats from Terminal. plugin, but it still work.
Inside NVIM I see error every 10 seconds(with enabled debug):
```
 Error detected while processing function <SNR>24_NeovimAsyncExitHandler:                                                       
line    6:
[WakaTime] Error 1: Traceback (most recent call last):^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/cli.py", line 24, in <module>^@    import wakatime^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/__init__.py", line 17, in <module>^@    from .main import execute^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/main.py", line 24, in <module>^@    from .api import send_heartbeats^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/api.py", line 22, in <module>^@    from .packages.requests.exceptions import RequestException^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/packages/requests/__init__.py", line 98, in <module>^@    from . import packages^@ImportError: bad magic number in 'wakatime.packages.requests.packages': b'\x03\xf3\r\n'^@^@During handling of the above exception, another exception occurred:^@^@Traceback (most recent call last):^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/cli.py", line 31, in <module>^@    import wakatime^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/__init__.py", line 17, in <module>^@    from .main import execute^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/main.py", line 24, in <module>^@    from .api import send_heartbeats^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/api.py", line 23, in <module>^@    from .session_cache import SessionCache^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/session_cache.py", line 26, in <module>^@    from .packages import requests^@  File "/Users/username/.config/nvim/plugged/vim-wakatime/plugin/packages/wakatime/packages/requests/__init__.py", line 98, in <module>^@    from . import packages^@ImportError: bad magic number in 'wakatime.packages.requests.packages': b'\x03\xf3\r\n'^@
```

I use macos 10.13.3, NVIM v0.2.2(Build type: Release), plugin version '7.0.5'

**Comment by alanhamlett** [comment]
That file (wakatime.packages.requests.packages) hasn't changed since `6.0.3 (2017-10-29)`, so not sure what would have changed recently to cause this error.

If you delete `/Users/username/.config/nvim/plugged/vim-wakatime` and re-install the vim-wakatime plugin does that fix it?

**Comment by sovetnik** [comment]
Yes, remove folder and reinstall solve this. 
Before I tried previous commits and reinstall from Plug.
Maybe add to README note about manual reinstall?
And thank you. Twice )
